/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretariasRouteImport } from './routes/secretarias'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as NovaVendaRouteImport } from './routes/nova-venda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditarVendaIdRouteImport } from './routes/editar-venda.$id'

const SecretariasRoute = SecretariasRouteImport.update({
  id: '/secretarias',
  path: '/secretarias',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaVendaRoute = NovaVendaRouteImport.update({
  id: '/nova-venda',
  path: '/nova-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarVendaIdRoute = EditarVendaIdRouteImport.update({
  id: '/editar-venda/$id',
  path: '/editar-venda/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nova-venda': typeof NovaVendaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/secretarias': typeof SecretariasRoute
  '/editar-venda/$id': typeof EditarVendaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nova-venda': typeof NovaVendaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/secretarias': typeof SecretariasRoute
  '/editar-venda/$id': typeof EditarVendaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nova-venda': typeof NovaVendaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/secretarias': typeof SecretariasRoute
  '/editar-venda/$id': typeof EditarVendaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nova-venda'
    | '/produtos'
    | '/relatorios'
    | '/secretarias'
    | '/editar-venda/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nova-venda'
    | '/produtos'
    | '/relatorios'
    | '/secretarias'
    | '/editar-venda/$id'
  id:
    | '__root__'
    | '/'
    | '/nova-venda'
    | '/produtos'
    | '/relatorios'
    | '/secretarias'
    | '/editar-venda/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovaVendaRoute: typeof NovaVendaRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SecretariasRoute: typeof SecretariasRoute
  EditarVendaIdRoute: typeof EditarVendaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretarias': {
      id: '/secretarias'
      path: '/secretarias'
      fullPath: '/secretarias'
      preLoaderRoute: typeof SecretariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-venda': {
      id: '/nova-venda'
      path: '/nova-venda'
      fullPath: '/nova-venda'
      preLoaderRoute: typeof NovaVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-venda/$id': {
      id: '/editar-venda/$id'
      path: '/editar-venda/$id'
      fullPath: '/editar-venda/$id'
      preLoaderRoute: typeof EditarVendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovaVendaRoute: NovaVendaRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SecretariasRoute: SecretariasRoute,
  EditarVendaIdRoute: EditarVendaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
